name: build

on:
  push:
    branches:
      - main
  pull_request:
concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - run: chmod +x gradlew

      - name: Apply spotless Formatting
        run: ./gradlew spotlessApply --stacktrace

      - name: Apply ktlint Formatting
        run: ./gradlew ktlintFormat --stacktrace

      - name: Check lint
        run: ./gradlew lintDebug --stacktrace

      - name: Build debug build variant
        run: ./gradlew assembleDebug --stacktrace

      - name: Run local tests
        run: ./gradlew testDebugUnitTest --stacktrace
